name: "Run Noxtara Scan"
description: "Run SCA/SAST security scans using @noxtara/cli"
author: "xcidic"
branding:
  icon: "shield"
  color: "blue"

inputs:
  api-key:
    description: "Noxtara API key for authentication"
    required: true
  base-url:
    description: "Noxtara API base URL"
    required: false
    default: "https://app.noxtara.com/api/main/client"
  working-directory:
    description: "Directory to scan (relative to repository root)"
    required: false
    default: "."
  cli-version:
    description: "Version of @noxtara/cli to use"
    required: false
    default: "latest"
  auto-pr:
    description: "Automatically create PRs to update config with new entry IDs (requires gh CLI)"
    required: false
    default: "true"
  github-token:
    description: "GitHub token for creating PRs (auto-pr feature). Defaults to GITHUB_TOKEN."
    required: false

runs:
  using: "composite"
  steps:
    - name: Check Runner OS
      shell: bash
      run: |
        if [[ "${{ runner.os }}" != "Linux" ]]; then
          echo "Error: This action only supports Linux runners. Current OS: ${{ runner.os }}"
          exit 1
        fi
        echo "Running on Linux"

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: "24"

    - name: Install Noxtara CLI
      shell: bash
      run: npm install -g @noxtara/cli@${{ inputs.cli-version }}

    - name: Run Noxtara Scan
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: noxtara scan
      env:
        NOXTARA_API_KEY: ${{ inputs.api-key }}
        NOXTARA_BASE_URL: ${{ inputs.base-url }}
        NOXTARA_AUTO_PR: ${{ inputs.auto-pr }}
        GH_TOKEN: ${{ inputs.github-token || github.token }}
